### ISSUE TITLE
Get something like Dependabot configured

### ISSUE THREAD

**Issue by caseyhelbling** [minnestar/sessionizer#225]
https://dependabot.com/

Let's do a better job of keeping our dependencies up to date.

**Comment by Mirv** [comment]
I poked it briefly last night ...

**Issue**

> Repo must contain either a Gemfile, a gemspec, or a gems.rb.

**Expected**

Said files are in the project root

**Actual**

Files are in `/src`

**Recommendation**

Customize dependabot configuration which allows project to continue on unmodified.

**Steps**

Create directory with yaml file as below ...

`.dependabot/config.yml` 

Configure alternative location in file for the ruby gemfile ...

```
version: 1
update_configs:
  # custom dependency file to allow build process on sessionizer for vag/ansible
  - package_manager: "ruby:bundler"
    directory: "/src"
    update_schedule: "live"
```

I generally program from a cloud ide - so I haven't setup my test box at home in awhile & haven't syntax checked this one.  Thus no time spent on a PR.  

---
As it stands the process makes a github issue everytime there's a needed update.

I'm also guessing you want someone to map out the dependency auto updating process in a safe manner?  Which can get a bit subjective so I'm leaving it for now.

```
Example: automerge based on dependency type
version: 1
update_configs:
  # required properties omitted ...
  automerged_updates:
    - match:
        dependency_type: "development"
        # Supported dependency types:
        # - "development"
        # - "production"
        # - "all"
        update_type: "all"
        # Supported updates to automerge:
        # - "security:patch"
        #   SemVer patch update that fixes a known security vulnerability
        # - "semver:patch"
        #   SemVer patch update, e.g. > 1.x && 1.0.1 to 1.0.3
        # - "semver:minor"
        #   SemVer minor update, e.g. > 1.x && 2.1.4 to 2.3.1
        # - "in_range"
        #   matching the version requirement in your package manifest
        # - "all"
    - match:
        dependency_type: "production"
        update_type: "semver:patch"
```
